name: Launch EC2 and Run Tests

on:
  push:
    branches:
      - main

jobs:
  launch-ec2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List repository contents
        run: ls -R

      - name: Use private key
        run: chmod 400 keys/2_26_2025.pem

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Create temporary EC2 instance
        id: create-ec2
        run: |
          INSTANCE_ID=$(aws ec2 run-instances \
            --image-id ami-04b4f1a9cf54c11d0 \
            --count 1 \
            --instance-type t2.medium \
            --key-name "2/26/2025" \
            --security-group-ids sg-00815fc516a8e3401 \
            --tag-specifications 'ResourceType=instance,Tags=[{Key=Name,Value=TempInstance}]' \
            --query 'Instances[0].InstanceId' \
            --output text)
          echo "::set-output name=instance_id::$INSTANCE_ID"
          aws ec2 wait instance-running --instance-ids $INSTANCE_ID
          PUBLIC_IP=$(aws ec2 describe-instances --instance-ids $INSTANCE_ID --query 'Reservations[0].Instances[0].PublicIpAddress' --output text)
          echo "::set-output name=public_ip::$PUBLIC_IP"

      - name: Wait for EC2 Running
        run: aws ec2 wait instance-status-ok --instance-ids ${{ steps.create-ec2.outputs.instance_id }}

      - name: Install dependencies on EC2 instance
        run: |
          ssh -o StrictHostKeyChecking=no -i keys/2_26_2025.pem ubuntu@${{ steps.create-ec2.outputs.public_ip }} << 'EOF'
          # Add Docker's official GPG key:
          sudo apt-get update
          sudo apt-get install ca-certificates curl
          sudo install -m 0755 -d /etc/apt/keyrings
          sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
          sudo chmod a+r /etc/apt/keyrings/docker.asc

          # Add the repository to Apt sources:
          echo \
          "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
          $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}") stable" | \
          sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get update
          sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugi
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version
          sudo apt install python3  
          sudo apt install python3-pip
          sudo pip install awscli --break-system-packages
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key = ${{ secrets.AWS_SESSION_TOKEN }}" >> ~/.aws/credentials
          echo "aws_session_token = ${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials
          echo "region = ${{ secrets.AWS_REGION }}" >> ~/.aws/credentials
          EOF

      - name: Transfer Docker Compose file and script to EC2 instance
        run: |
          scp -o StrictHostKeyChecking=no -i keys/2_26_2025.pem SmokeTest/docker-compose.yml ubuntu@${{ steps.create-ec2.outputs.public_ip }}:~
          scp -o StrictHostKeyChecking=no -i keys/2_26_2025.pem SmokeTest/script.sh ubuntu@${{ steps.create-ec2.outputs.public_ip }}:~

      - name: Make script executable and run it
        run: |
          ssh -o StrictHostKeyChecking=no -i keys/2_26_2025.pem ubuntu@${{ steps.create-ec2.outputs.public_ip }} "chmod +x ~/script.sh && ~/script.sh"

      - name: Terminate temporary EC2 instance
        if: always()
        run: |
          aws ec2 terminate-instances --instance-ids ${{ steps.create-ec2.outputs.instance_id }}
          aws ec2 wait instance-terminated --instance-ids ${{ steps.create-ec2.outputs.instance_id }}
